dataset_root: datasets
dataset_name: ReplicaReID

segmentation_type: maskrcnn
object_backbone: resnet50
segmentation_threshold: 0.60

overwrite: true

num_references: 3
reference_selection_mode: closest_to_center